apiVersion: v1
kind: Service
metadata:
  name: react-app-service
spec:
  type: NodePort
  selector:
    app: react-app
  ports:
    - protocol: TCP
      port: 80      # Internal container port
      targetPort: 80  # Container's exposed port
      nodePort: 30009 # Externally accessible port (must be in range 30000-32767)
